import{a as d,S as f,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const m="https://pixabay.com/api/",p="53360876-f97dd2c70b0e27b498deb3edc";async function y(n){const o={key:p,q:n,image_tнpe:"photo",orientation:"horizontal",safesearch:!0};return(await d.get(m,{params:o})).data}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),h=new f(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const o=n.map(e=>`
            <a class="gallery-item" href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            <div class="info">
                <p><b>Likes:</b> ${e.likes}</p>
                <p><b>Views:</b> ${e.views}</p>
                <p><b>Comments:</b> ${e.comments}</p>
                <p><b>Downloads:</b> ${e.downloads}</p>
            </div>
            </a>`).join("");l.insertAdjacentHTML("beforeend",o),h.refresh()}function b(){l.innerHTML=""}function L(){u.classList.remove("hidden")}function w(){u.classList.add("hidden")}const c=document.querySelector(".form"),S=document.querySelector("input[name='search-text']");c.addEventListener("submit",async n=>{n.preventDefault();const o=S.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query!",timeout:2e3});return}b(),L();try{const e=await y(o);if(!e.hits||e.hits.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits)}catch{a.error({title:"Error",message:"Something went wrong! Try again later."})}finally{w(),c.reset()}});
//# sourceMappingURL=index.js.map
